<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <StartupObject>DumpPacksProgram</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="DumpPacksProgram.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\launcher\SMSO.Net\SMSO.Net.csproj" />
  </ItemGroup>
</Project>
